language: node_js
node_js: node
sudo: false
after_success:
  - npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 647b......fce9
    secure: hW+sOEa83U4mmrgxUXlxM1A4pYNwwhjT2fAgTGECHJp23CSR7dKLAu8Fl8kt5JvAEvPttJFWSFbUpQhxVc2dSziDcVZ3YP4NOlknP/82l8Dh7kt75srRQRdGVUzYjSoP+e7OB9tTPZ7fIesagWMsP+xHLpNhIFvVQFWPWhvxL8U=
  on:
    tags: true
    repo: Brightspace/frau-locale-provider
