language: node_js
node_js:
- '0.10'
sudo: false
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: Xa3GrxtuwAwKS9Y8hT10XGzKTZcaZxPInOvvJGr4prqAS4u3LiE979pIY6y5mmtCpBx2VaqO5jPnuHgaa+hGy4aM8erVkAooq/+DW3ZYfA/MIm8kOJ2SVCxiXW8ZNYWO/ZITqJvmGBK/JY8Mz6NUdGyb3wS8kZwOLT6xbgp8yPM=
  on:
    tags: true
    repo: Brightspace/frau-locale-provider
    all_branches: true
