language: node_js
node_js: node
sudo: false
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: g3HH1nQFw8wtWh3aKV0MD4xM+PfzMW4mtEYmiYWG2TBcDIqgVvomysS9GcxZ0WdhFkokcsyZRoNHIVIwqdxjW+HHtUmJUcBJ8/AvOmZRqVXRJiasIjuDhvBS3p+BTsOVEUOD05RZcWhs0MnKyJ3VXauTr9ZgdZHAj0VeR0UnorQ=
  on:
    tags: true
    repo: Brightspace/frau-locale-provider
