language: node_js
node_js:
- '0.10'
sudo: false
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: AGc9V+jAJBaDeQGLadnshQeToP1oMzULY7qKXiOr0XR5OsZanzwc0oTuszzg4NzxI53n6TH1Ev/W4nurlTQ8fQtOA/VEycIBLwEW4k1gveaEiyXjkANJp1I6cztqAHIP5jQsgeNOjWDpftyEvCEg6fvDl21/Fw5eUvqaNIPF7DI=
  on:
    tags: true
    repo: Brightspace/frau-locale-provider
    all_branches: true
